/**
 * UniLib - Initial Seed Data for Academic Library
 */

import { Book, User, Loan, Reservation, ReadingProgressItem } from '@/types';
import { calculateDueDate } from './dateUtils';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-student-01',
    name: 'Sofia Delgado',
    email: 'sofia.delgado@unilib.edu',
    role: 'STUDENT',
    studentOrEmployeeId: 'ST-2024-8841',
    department: 'Computer Science & Software Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
    maxBorrowLimit: 5,
    joinedDate: '2024-01-15',
  },
  {
    id: 'user-prof-02',
    name: 'Dr. Alejandro Rossi',
    email: 'a.rossi@unilib.edu',
    role: 'PROFESSOR',
    studentOrEmployeeId: 'PF-1092-CS',
    department: 'Faculty of Natural Sciences & Computing',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    maxBorrowLimit: 15,
    joinedDate: '2019-08-20',
  },
  {
    id: 'user-librarian-03',
    name: 'Elena Vega',
    email: 'elena.vega@unilib.edu',
    role: 'LIBRARIAN',
    studentOrEmployeeId: 'LIB-0044',
    department: 'University Central Library Services',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    maxBorrowLimit: 25,
    joinedDate: '2017-03-10',
  },
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'OL82563W',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    authors: ['Robert C. Martin'],
    coverUrl: 'https://covers.openlibrary.org/b/id/9255566-L.jpg',
    firstPublishYear: 2008,
    subjects: ['Computer Science', 'Software Engineering', 'Agile', 'Programming'],
    description: 'Even bad code can function. But if code isn\'t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. This book presents revolutionary best practices of cleaning code on the fly.',
    isbn: '9780132350884',
    publisher: 'Prentice Hall',
    pageCount: 464,
    averageRating: 4.7,
    ratingsCount: 320,
    availabilityStatus: 'ON_LOAN',
    totalCopies: 4,
    availableCopies: 0,
    locationShelf: 'CS-Floor 2-Row 4-A',
  },
  {
    id: 'OL27479W',
    title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
    authors: ['Erich Gamma', 'Richard Helm', 'Ralph Johnson', 'John Vlissides'],
    coverUrl: 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
    firstPublishYear: 1994,
    subjects: ['Computer Science', 'Software Architecture', 'Object Oriented Programming'],
    description: 'Capturing a wealth of experience about the design of object-oriented software, four top-notch designers present a catalog of simple and succinct solutions to commonly occurring design problems.',
    isbn: '9780201633610',
    publisher: 'Addison-Wesley',
    pageCount: 395,
    averageRating: 4.8,
    ratingsCount: 410,
    availabilityStatus: 'AVAILABLE',
    totalCopies: 5,
    availableCopies: 3,
    locationShelf: 'CS-Floor 2-Row 4-B',
  },
  {
    id: 'OL3389283W',
    title: 'Introduction to Algorithms (CLRS)',
    authors: ['Thomas H. Cormen', 'Charles E. Leiserson', 'Ronald L. Rivest', 'Clifford Stein'],
    coverUrl: 'https://covers.openlibrary.org/b/id/12843460-L.jpg',
    firstPublishYear: 1990,
    subjects: ['Computer Science', 'Algorithms', 'Data Structures', 'Mathematics'],
    description: 'Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor. Introduction to Algorithms uniquely combines rigor and comprehensiveness across sorting, graph theory, dynamic programming, and greedy algorithms.',
    isbn: '9780262033848',
    publisher: 'MIT Press',
    pageCount: 1312,
    averageRating: 4.9,
    ratingsCount: 650,
    availabilityStatus: 'AVAILABLE',
    totalCopies: 6,
    availableCopies: 2,
    locationShelf: 'CS-Floor 2-Row 5-C',
  },
  {
    id: 'OL262758W',
    title: 'A Brief History of Time',
    authors: ['Stephen Hawking'],
    coverUrl: 'https://covers.openlibrary.org/b/id/10521270-L.jpg',
    firstPublishYear: 1988,
    subjects: ['Science & Physics', 'Cosmology', 'Space', 'Theoretical Physics'],
    description: 'A landmark volume in science writing by one of the great minds of our time, Stephen Hawking explores profound questions about the universe: How did the universe begin? What makes it tick? Can time run backwards? And how will it end?',
    isbn: '9780553380163',
    publisher: 'Bantam Books',
    pageCount: 256,
    averageRating: 4.6,
    ratingsCount: 520,
    availabilityStatus: 'AVAILABLE',
    totalCopies: 3,
    availableCopies: 1,
    locationShelf: 'SCI-Floor 3-Row 1-A',
  },
  {
    id: 'OL2163533W',
    title: 'Sapiens: A Brief History of Humankind',
    authors: ['Yuval Noah Harari'],
    coverUrl: 'https://covers.openlibrary.org/b/id/8775466-L.jpg',
    firstPublishYear: 2011,
    subjects: ['History & Civilization', 'Anthropology', 'Evolution', 'Sociology'],
    description: 'One hundred thousand years ago, at least six human species inhabited the earth. Today there is just one: Homo sapiens. How did our species succeed in the battle for dominance? An international bestseller exploring human cultural and biological history.',
    isbn: '9780062316097',
    publisher: 'Harper',
    pageCount: 464,
    averageRating: 4.7,
    ratingsCount: 980,
    availabilityStatus: 'RESERVED',
    totalCopies: 4,
    availableCopies: 0,
    locationShelf: 'HIST-Floor 1-Row 3-D',
  },
  {
    id: 'OL102749W',
    title: 'The Republic',
    authors: ['Plato'],
    coverUrl: 'https://covers.openlibrary.org/b/id/8231856-L.jpg',
    firstPublishYear: -375,
    subjects: ['Philosophy & Ethics', 'Political Science', 'Classics'],
    description: 'Plato\'s masterwork concerning justice, the order and character of the just city-state, and the just human being. It includes the famous Allegory of the Cave and foundational inquiries into the nature of knowledge, virtue, and education.',
    isbn: '9780140455113',
    publisher: 'Penguin Classics',
    pageCount: 448,
    averageRating: 4.4,
    ratingsCount: 310,
    availabilityStatus: 'AVAILABLE',
    totalCopies: 4,
    availableCopies: 4,
    locationShelf: 'PHIL-Floor 1-Row 8-B',
  },
  {
    id: 'OL15444315W',
    title: 'Don Quixote',
    authors: ['Miguel de Cervantes Saavedra'],
    coverUrl: 'https://covers.openlibrary.org/b/id/12586715-L.jpg',
    firstPublishYear: 1605,
    subjects: ['Literature & Poetry', 'Spanish Literature', 'Fiction', 'Satire'],
    description: 'The epic story of the ingenious gentleman of La Mancha, who, driven by chivalric romances, sets out with his loyal squire Sancho Panza to right the wrongs of the world. One of the pinnacle literary achievements of human history.',
    isbn: '9780060934347',
    publisher: 'Ecco',
    pageCount: 992,
    averageRating: 4.5,
    ratingsCount: 420,
    availabilityStatus: 'AVAILABLE',
    totalCopies: 3,
    availableCopies: 2,
    locationShelf: 'LIT-Floor 4-Row 2-C',
  },
  {
    id: 'OL276943W',
    title: 'Structure and Interpretation of Computer Programs',
    authors: ['Harold Abelson', 'Gerald Jay Sussman'],
    coverUrl: 'https://covers.openlibrary.org/b/id/11171802-L.jpg',
    firstPublishYear: 1984,
    subjects: ['Computer Science', 'Lisp', 'Functional Programming', 'Computing'],
    description: 'Known affectionately as the Wizard Book, this legendary MIT textbook challenges students to master computational models, data abstraction, and interpreter design through Scheme.',
    isbn: '9780262510875',
    publisher: 'MIT Press',
    pageCount: 657,
    averageRating: 4.9,
    ratingsCount: 390,
    availabilityStatus: 'AVAILABLE',
    totalCopies: 2,
    availableCopies: 1,
    locationShelf: 'CS-Floor 2-Row 5-D',
  }
];

export const INITIAL_LOANS: Loan[] = [
  {
    id: 'loan-001',
    bookId: 'OL82563W',
    bookTitle: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    bookCoverUrl: 'https://covers.openlibrary.org/b/id/9255566-L.jpg',
    bookAuthors: ['Robert C. Martin'],
    userId: 'user-student-01',
    userName: 'Sofia Delgado',
    userRole: 'STUDENT',
    borrowDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: calculateDueDate(new Date(Date.now() - 11 * 24 * 60 * 60 * 1000), 14), // 3 days remaining!
    status: 'ACTIVE',
    renewCount: 0,
  },
  {
    id: 'loan-002',
    bookId: 'OL262758W',
    bookTitle: 'A Brief History of Time',
    bookCoverUrl: 'https://covers.openlibrary.org/b/id/10521270-L.jpg',
    bookAuthors: ['Stephen Hawking'],
    userId: 'user-student-01',
    userName: 'Sofia Delgado',
    userRole: 'STUDENT',
    borrowDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: calculateDueDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), 14), // 11 days remaining!
    status: 'ACTIVE',
    renewCount: 0,
  },
  {
    id: 'loan-003',
    bookId: 'OL102749W',
    bookTitle: 'The Republic',
    bookCoverUrl: 'https://covers.openlibrary.org/b/id/8231856-L.jpg',
    bookAuthors: ['Plato'],
    userId: 'user-student-01',
    userName: 'Sofia Delgado',
    userRole: 'STUDENT',
    borrowDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    returnDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'RETURNED',
    renewCount: 0,
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-001',
    bookId: 'OL2163533W',
    bookTitle: 'Sapiens: A Brief History of Humankind',
    bookCoverUrl: 'https://covers.openlibrary.org/b/id/8775466-L.jpg',
    userId: 'user-student-01',
    userName: 'Sofia Delgado',
    reservationDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    queuePosition: 1,
    status: 'PENDING',
  },
];

export const INITIAL_READING_ITEMS: ReadingProgressItem[] = [
  {
    id: 'rp-001',
    bookId: 'OL82563W',
    bookTitle: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    bookCoverUrl: 'https://covers.openlibrary.org/b/id/9255566-L.jpg',
    bookAuthors: ['Robert C. Martin'],
    userId: 'user-student-01',
    status: 'READING',
    progressPercentage: 65,
    notes: 'Focusing on chapter 6 on objects and data structures.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rp-002',
    bookId: 'OL102749W',
    bookTitle: 'The Republic',
    bookCoverUrl: 'https://covers.openlibrary.org/b/id/8231856-L.jpg',
    bookAuthors: ['Plato'],
    userId: 'user-student-01',
    status: 'COMPLETED',
    progressPercentage: 100,
    rating: 5,
    notes: 'Finished for Philosophy 101 seminar.',
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
